apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
#        livenessProbe:
#          httpGet:
#            path: /wps/myportal
#            port: {{ .Values.service.internalPort }}
#          initialDelaySeconds: {{ .Values.service.probe.delaySeconds }}
#          periodSeconds: {{ .Values.service.probe.periodSeconds }}
#          failureThreshold: {{ .Values.service.probe.failureThreshold }}
#          timeoutSeconds: {{ .Values.service.probe.timeoutSeconds }}
#        readinessProbe:
#          httpGet:
#            path: /wps/myportal
#            port: {{ .Values.service.internalPort }}
#          initialDelaySeconds: {{ .Values.service.probe.delaySeconds }}
#          periodSeconds: {{ .Values.service.probe.periodSeconds }}
#          failureThreshold: {{ .Values.service.probe.failureThreshold }}
#          timeoutSeconds: {{ .Values.service.probe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
